name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync to Hugging Face Hub
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
        run: |
          git push https://huggingface:$HUGGINGFACE_TOKEN@huggingface.co/spaces/SunYoung123/code-generator main